package nsu.fit.exception;

public enum ErrorType {

    USER_NOT_FOUND,
    SETTINGS_NOT_FOUND,
    USER_NICKNAME_OCCUPIED,
    SELF_FRIEND_REQUEST,
    FRIEND_REQUEST_ALREADY_PENDING,
    FRIEND_REQUEST_NOT_FOUND,
    FRIENDSHIP_ALREADY_EXIST

}
