CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    nickname VARCHAR(30) UNIQUE NOT NULL,
    name VARCHAR(20) NOT NULL,
    password VARCHAR(256) NOT NULL
);

CREATE TABLE wish (
    id SERIAL PRIMARY KEY,
    sender_id INT NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    receiver_id INT REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    message VARCHAR(256) NOT NULL,
    anonymous BOOLEAN NOT NULL
);

CREATE TABLE settings (
    user_id INT PRIMARY KEY REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    message_type VARCHAR(50) NOT NULL
);

CREATE TABLE friend_request (
    id SERIAL PRIMARY KEY,
    sender_id INT NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    receiver_id INT NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE friendship (
    id SERIAL PRIMARY KEY,
    fst_user_id INT NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    snd_user_id INT NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);