services:
  postgres:
    build: ..
    container_name: inspira-postgres-local
    command: [ "postgres", "-c", "log_statement=all" ]
    image: inspira-postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass
      POSTGRES_DB: inspira_db
    restart: always