server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: JwtAuthFilter
          args:
            ignoredPaths:
              - /api/users/login
              - /api/users/register
      routes:
        - id: user-service
          uri: http://user:8081
          predicates:
            - Path=/api/users/**
        - id: message-service
          uri: http://message:8082
          predicates:
            - Path=/api/messages/**
        - id: llm-service
          uri: http://llm:8083
          predicates:
            - Path=/api/llm/**

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
